//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Model.Persistence
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PersistenceEntities : ObjectContext
    {
    	#region Constructors
    
    	/// <summary>
    	/// Initializes a new PersistenceEntities object using the connection string found in the 'PersistenceEntities' section of the application configuration file.
    	/// </summary>
    	public PersistenceEntities() : base("name=PersistenceEntities", "PersistenceEntities")
    	{
    		this.ContextOptions.LazyLoadingEnabled = true;
    		OnContextCreated();
    	}
    
    	/// <summary>
    	/// Initialize a new PersistenceEntities object.
    	/// </summary>
    	public PersistenceEntities(string connectionString) : base(connectionString, "PersistenceEntities")
    	{
    		this.ContextOptions.LazyLoadingEnabled = true;
    		OnContextCreated();
    	}
    
    	/// <summary>
    	/// Initialize a new PersistenceEntities object.
    	/// </summary>
    	public PersistenceEntities(EntityConnection connection) : base(connection, "PersistenceEntities")
    	{
    		this.ContextOptions.LazyLoadingEnabled = true;
    		OnContextCreated();
    	}
    
    	#endregion
    
    	#region Partial Methods
    
    	partial void OnContextCreated();
    
    	#endregion
    
        #region ObjectSet Properties
    
    	/// <summary>
    	/// No Metadata Documentation available.
    	/// </summary>
    	public ObjectSet<Advertisement> Advertisements
    	{
    		get
    		{
    			if ((_Advertisements == null))
    			{
    				_Advertisements = base.CreateObjectSet<Advertisement>("Advertisements");
    			}
    			return _Advertisements;
    		}
    	}
    	private ObjectSet<Advertisement> _Advertisements;
    
    	/// <summary>
    	/// No Metadata Documentation available.
    	/// </summary>
    	public ObjectSet<DotNetConvertibleLocation> DotNetConvertibleLocations
    	{
    		get
    		{
    			if ((_DotNetConvertibleLocations == null))
    			{
    				_DotNetConvertibleLocations = base.CreateObjectSet<DotNetConvertibleLocation>("DotNetConvertibleLocations");
    			}
    			return _DotNetConvertibleLocations;
    		}
    	}
    	private ObjectSet<DotNetConvertibleLocation> _DotNetConvertibleLocations;
    
    	/// <summary>
    	/// No Metadata Documentation available.
    	/// </summary>
    	public ObjectSet<Location> Locations
    	{
    		get
    		{
    			if ((_Locations == null))
    			{
    				_Locations = base.CreateObjectSet<Location>("Locations");
    			}
    			return _Locations;
    		}
    	}
    	private ObjectSet<Location> _Locations;

        #endregion
        #region AddTo Methods
    
    	/// <summary>
    	/// Deprecated Method for adding a new object to the Advertisements EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
    	/// </summary>
    	public void AddToAdvertisements(Advertisement advertisement)
    	{
    		base.AddObject("Advertisements", advertisement);
    	}
    
    	/// <summary>
    	/// Deprecated Method for adding a new object to the DotNetConvertibleLocations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
    	/// </summary>
    	public void AddToDotNetConvertibleLocations(DotNetConvertibleLocation dotNetConvertibleLocation)
    	{
    		base.AddObject("DotNetConvertibleLocations", dotNetConvertibleLocation);
    	}
    
    	/// <summary>
    	/// Deprecated Method for adding a new object to the Locations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
    	/// </summary>
    	public void AddToLocations(Location location)
    	{
    		base.AddObject("Locations", location);
    	}

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Persistence", Name="Advertisement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Advertisement : EntityObject
    {
        #region Factory Method
    
    	/// <summary>
    	/// Create a new Advertisement object.
    	/// </summary>
        /// <param name="identifier">Initial value of the Identifier property.</param>
    	public static Advertisement CreateAdvertisement(global::System.Int32 identifier)
    	{
    		Advertisement advertisement = new Advertisement();
    		advertisement.Identifier = identifier;
    		return advertisement;
    	}

        #endregion
        #region Primitive Properties
    
    	/// <summary>
    	/// No Metadata Documentation available.
    	/// </summary>
    	[EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    	[DataMemberAttribute()]
    	public global::System.Int32 Identifier
    	{
    		get
    		{
    			return _Identifier;
    		}
    		set
    		{
    			if (_Identifier != value)
    			{
        			OnIdentifierChanging(value);
        			ReportPropertyChanging("Identifier");
        			_Identifier = StructuralObject.SetValidValue(value);
        			ReportPropertyChanged("Identifier");
        			OnIdentifierChanged();
    			}
    		}
    	}
    	private global::System.Int32 _Identifier;
    	partial void OnIdentifierChanging(global::System.Int32 value);
    	partial void OnIdentifierChanged();
    
    	/// <summary>
    	/// No Metadata Documentation available.
    	/// </summary>
    	[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    	[DataMemberAttribute()]
    	public global::System.Byte[] Content
    	{
    		get
    		{
    			return StructuralObject.GetValidValue(_Content);
    		}
    		set
    		{
    			OnContentChanging(value);
    			ReportPropertyChanging("Content");
    			_Content = StructuralObject.SetValidValue(value, true);
    			ReportPropertyChanged("Content");
    			OnContentChanged();
    		}
    	}
    	private global::System.Byte[] _Content;
    	partial void OnContentChanging(global::System.Byte[] value);
    	partial void OnContentChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Persistence", Name="DotNetConvertibleLocation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DotNetConvertibleLocation : EntityObject
    {
        #region Factory Method
    
    	/// <summary>
    	/// Create a new DotNetConvertibleLocation object.
    	/// </summary>
        /// <param name="identifier">Initial value of the Identifier property.</param>
    	public static DotNetConvertibleLocation CreateDotNetConvertibleLocation(global::System.Int32 identifier)
    	{
    		DotNetConvertibleLocation dotNetConvertibleLocation = new DotNetConvertibleLocation();
    		dotNetConvertibleLocation.Identifier = identifier;
    		return dotNetConvertibleLocation;
    	}

        #endregion
        #region Primitive Properties
    
    	/// <summary>
    	/// No Metadata Documentation available.
    	/// </summary>
    	[EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    	[DataMemberAttribute()]
    	public global::System.Int32 Identifier
    	{
    		get
    		{
    			return _Identifier;
    		}
    		set
    		{
    			if (_Identifier != value)
    			{
        			OnIdentifierChanging(value);
        			ReportPropertyChanging("Identifier");
        			_Identifier = StructuralObject.SetValidValue(value);
        			ReportPropertyChanged("Identifier");
        			OnIdentifierChanged();
    			}
    		}
    	}
    	private global::System.Int32 _Identifier;
    	partial void OnIdentifierChanging(global::System.Int32 value);
    	partial void OnIdentifierChanged();
    
    	/// <summary>
    	/// No Metadata Documentation available.
    	/// </summary>
    	[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    	[DataMemberAttribute()]
    	public global::System.String PhoneId
    	{
    		get
    		{
    			return _PhoneId;
    		}
    		set
    		{
    			OnPhoneIdChanging(value);
    			ReportPropertyChanging("PhoneId");
    			_PhoneId = StructuralObject.SetValidValue(value, true);
    			ReportPropertyChanged("PhoneId");
    			OnPhoneIdChanged();
    		}
    	}
    	private global::System.String _PhoneId;
    	partial void OnPhoneIdChanging(global::System.String value);
    	partial void OnPhoneIdChanged();
    
    	/// <summary>
    	/// No Metadata Documentation available.
    	/// </summary>
    	[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    	[DataMemberAttribute()]
    	public global::System.Byte[] Location
    	{
    		get
    		{
    			return StructuralObject.GetValidValue(_Location);
    		}
    		set
    		{
    			OnLocationChanging(value);
    			ReportPropertyChanging("Location");
    			_Location = StructuralObject.SetValidValue(value, true);
    			ReportPropertyChanged("Location");
    			OnLocationChanged();
    		}
    	}
    	private global::System.Byte[] _Location;
    	partial void OnLocationChanging(global::System.Byte[] value);
    	partial void OnLocationChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Persistence", Name="Location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Location : EntityObject
    {
        #region Factory Method
    
    	/// <summary>
    	/// Create a new Location object.
    	/// </summary>
        /// <param name="identifier">Initial value of the Identifier property.</param>
    	public static Location CreateLocation(global::System.Int64 identifier)
    	{
    		Location location = new Location();
    		location.Identifier = identifier;
    		return location;
    	}

        #endregion
        #region Primitive Properties
    
    	/// <summary>
    	/// No Metadata Documentation available.
    	/// </summary>
    	[EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    	[DataMemberAttribute()]
    	public global::System.Int64 Identifier
    	{
    		get
    		{
    			return _Identifier;
    		}
    		set
    		{
    			if (_Identifier != value)
    			{
        			OnIdentifierChanging(value);
        			ReportPropertyChanging("Identifier");
        			_Identifier = StructuralObject.SetValidValue(value);
        			ReportPropertyChanged("Identifier");
        			OnIdentifierChanged();
    			}
    		}
    	}
    	private global::System.Int64 _Identifier;
    	partial void OnIdentifierChanging(global::System.Int64 value);
    	partial void OnIdentifierChanged();
    
    	/// <summary>
    	/// No Metadata Documentation available.
    	/// </summary>
    	[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    	[DataMemberAttribute()]
    	public global::System.String PhoneId
    	{
    		get
    		{
    			return _PhoneId;
    		}
    		set
    		{
    			OnPhoneIdChanging(value);
    			ReportPropertyChanging("PhoneId");
    			_PhoneId = StructuralObject.SetValidValue(value, true);
    			ReportPropertyChanged("PhoneId");
    			OnPhoneIdChanged();
    		}
    	}
    	private global::System.String _PhoneId;
    	partial void OnPhoneIdChanging(global::System.String value);
    	partial void OnPhoneIdChanged();
    
    	/// <summary>
    	/// No Metadata Documentation available.
    	/// </summary>
    	[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    	[DataMemberAttribute()]
    	public global::System.String LocationText
    	{
    		get
    		{
    			return _LocationText;
    		}
    		set
    		{
    			OnLocationTextChanging(value);
    			ReportPropertyChanging("LocationText");
    			_LocationText = StructuralObject.SetValidValue(value, true);
    			ReportPropertyChanged("LocationText");
    			OnLocationTextChanged();
    		}
    	}
    	private global::System.String _LocationText;
    	partial void OnLocationTextChanging(global::System.String value);
    	partial void OnLocationTextChanged();

        #endregion
    
    }

    #endregion
    
}
